### ISSUE TITLE
Crate fails to build on Windows

### ISSUE THREAD

**Issue by retep998** [LordAldaron/dl_api#3]
```
error[E0432]: unresolved import `Error`
  --> C:\Users\appveyor\.cargo\registry\src\github.com-1ecc6299db9ec823\dl_api-0.3.0\src\library\windows.rs:14:5
   |
14 | use Error;
   |     ^^^^^ no `Error` external crate
```
Seems like you didn't test the edition upgrade on Windows. Do consider setting up CI for Windows on travis or appveyor to help catch these sort of things in the future.

**Comment by AldaronLau** [comment]
Doesn't that cost money?  I'll work on fixing this.

**Comment by retep998** [comment]
Travis and Appveyor both have free CI for open source projects, so this repo would qualify for their free plans.

**Comment by AldaronLau** [comment]
Thanks!  I think I understand Travis CI now, and version 0.3.1 is on crates.io now with the fix.
